### ISSUE TITLE
Fader Moves

### ISSUE THREAD

**Issue by jrviz** [bitfocus/companion-module-roland-m5000#1]
I'm part way through trying to get this module working with a serial connection into M-300 devices (which don't have an ethernet port). I'm running into a TCP Proxy with debug and I can see some commands sending but not absolute or relative fader moves. Is there a rogue extra comma in lines 1224 and 1234 of the current source where the command string  is being built?

**Comment by josephdadams** [comment]
Yep looks that way.

**Comment by josephdadams** [comment]
Fixed
