### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jrviz** [bitfocus/companion-module-roland-m5000#2]
I have this module working with a serial connection to an M-300 (so should work with M2,3,4 series with a serial connection). The module here is sending serial protocol messages via the TCP port for the M-5000, this is why it is possible. I have some of the features running (faders, mutes) for channels. One difference I see is the Mains in the M-5000 are MA1 and MA2, in the serial mixers they are MAL, MAR, MAC (Left, Right, Centre). Left and Right are a bonded stereo pair so actions on either L or R are on both as stereo. I think the mains on these mixers could be supported if one or both of MAL or MAR strings are pushed onto the CHOICES_CHANNELS_MAIN options array at initialisation. Is this possible? I'm happy to update the documentation for the module to point out the differences. 

I have the TCP to Serial bridging implemented by another open source component at the moment as the TCP-serial module has a problem in Windows at the moment. One it is fixed I will be trying with that. 

This module is great for bringing the lower cost (and older) Roland mixers into the Companion ecosystem.

**Comment by josephdadams** [comment]
@jrviz submit a PR for it :)

**Comment by jrviz** [comment]
OK, this will be a voyage of discovery! I have created a branch and a pull request. This is my first time so I hope this is correct.
Changes tested in local build (module-local-dev) using serial mixer simulator. Will test on Live mixer in church on Tuesday.

**Comment by josephdadams** [comment]
fixed in #3
